GET http://localhost:8000/get-user/
####
POST http://localhost:8000/new-user/
content-type: application/json

{
 "username":"TestUser","password":"user123", "email":"user1@gmail.com","age":20
}
####
DELETE http://localhost:8000/delete-user/65968d3670a710d9cf